services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "5173:8080"  # Jenkins accessible sur localhost:5173
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins_home:
