<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX1VSpkF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX1VSpkF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX1VSpkF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX1VSpkF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX1VSpkF\App_KernelDevDebugContainer([
    'container.build_hash' => 'X1VSpkF',
    'container.build_id' => 'f02543aa',
    'container.build_time' => 1737462374,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX1VSpkF');
